version: '3'

services:
  backend:
    build: ./backend
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ./backend:/app-back
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: db # Nome do service logo abaixo
      PORT: '3001'
      HOST: todo_list
    ports:
      - 3001:3001
    depends_on:
      db:
        condition: service_healthy
    networks:
      - todo_list_net

  db:
    image: mysql
    platform: linux/x86_64
    restart: always
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    networks:
      - todo_list_net

networks:
  todo_list_net:
    driver: bridge