version: '3'

services:
  backend:
    build: ./backend
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ./backend:/app-back
    env_file:
      - ./.env
    ports:
      - 3001:3001
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql
    platform: linux/x86_64
    restart: always
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10