version: '3'

services:
  web:
    build: ./frontend
    container_name: frontend
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ./frontend:/app-front
    ports:
      - 3000:3000
    networks:
      - todo_list_net
  
  api:
    build: ./backend
    container_name: backend
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ./backend:/app-back
    env_file:
      - ./.env
    ports:
      - 3001:3001
    depends_on:
      db:
        condition: service_healthy
    networks:
      - todo_list_net

  db:
    image: mysql
    container_name: db
    platform: linux/x86_64
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    networks:
      - todo_list_net

networks:
  todo_list_net:
    driver: bridge